// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaxxPv.Web.Models.Database;

#nullable disable

namespace SaxxPv.Web.Migrations
{
    [DbContext(typeof(Db))]
    [Migration("20251211091810_DayBattery_and_TotalImportExport")]
    partial class DayBattery_and_TotalImportExport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SaxxPv.Web.Models.Database.Pricing", b =>
                {
                    b.Property<DateTime>("From")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("To")
                        .HasColumnType("datetime2");

                    b.Property<double>("BuyPrice")
                        .HasColumnType("float");

                    b.Property<double>("SellPrice")
                        .HasColumnType("float");

                    b.HasKey("From", "To");

                    b.ToTable("Pricings");
                });

            modelBuilder.Entity("SaxxPv.Web.Models.Database.Reading", b =>
                {
                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("CurrentBattery")
                        .HasColumnType("float");

                    b.Property<double>("CurrentBatterySoc")
                        .HasColumnType("float");

                    b.Property<double>("CurrentGrid")
                        .HasColumnType("float");

                    b.Property<double>("CurrentLoad")
                        .HasColumnType("float");

                    b.Property<double>("CurrentPv")
                        .HasColumnType("float");

                    b.Property<double?>("DayBatteryCharge")
                        .HasColumnType("float");

                    b.Property<double?>("DayBatteryDischarge")
                        .HasColumnType("float");

                    b.Property<double>("DayBought")
                        .HasColumnType("float");

                    b.Property<double>("DayConsumption")
                        .HasColumnType("float");

                    b.Property<double>("DaySelfUse")
                        .HasColumnType("float");

                    b.Property<double>("DaySold")
                        .HasColumnType("float");

                    b.Property<double>("DayTotal")
                        .HasColumnType("float");

                    b.Property<double?>("TotalExport")
                        .HasColumnType("float");

                    b.Property<double?>("TotalImport")
                        .HasColumnType("float");

                    b.HasKey("DateTime");

                    b.ToTable("Readings");
                });
#pragma warning restore 612, 618
        }
    }
}
