name: SaxxPV Pipeline

env:
  VERSION: 1.1.0.${{ github.run_number }}

on:
  push:
    branches: 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    env: # Or as an environment variable
      Tables__ConnectionString: ${{ secrets.TABLES__CONNECTIONSTRING }}
      Sems__Username: ${{ secrets.SEMS__USERNAME }}
      Sems__Password: ${{ secrets.SEMS_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Test
        run: dotnet test --configuration Release
  
  build_and_deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Login to ghcr'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build'
        run: |
          docker build --tag ghcr.io/saxx/saxxpv:latest --tag ghcr.io/saxx/saxxpv:${{ env.VERSION }} --build-arg VERSION=${{ env.VERSION }} --file ./dockerfile .

      - name: 'Publish'
        run: |
          docker push ghcr.io/saxx/saxxpv:latest
          docker push ghcr.io/saxx/saxxpv:${{ env.VERSION }}
                  
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: saxxpv
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISHPROFILE }}
          images: ghcr.io/saxx/saxxpv:${{ env.VERSION }}

      
